version: '3.8'

services:
  auth-app:
    container_name: auth_app
    build:
      context: ../auth-app
    ports:
      - "4000:4000"
    env_file:
      - ./env/${ENV}.env

  api-app:
    container_name: api_app
    build:
      context: ../api-app
    ports:
      - "5001:5001"
    env_file:
      - ./env/${ENV}.env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: api_db
    ports:
      - "3306:3306"
    env_file:
      - ./env/${ENV}.env
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  db_data:
